name : Frontend CI
on:
  push:
    branches: [ main ]      # runs when you push to main or dev
  pull_request:
    branches: [ main ]
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./Frontend

      - name: Build Project
        run: npm run build
        working-directory: ./Frontend

      - name: Run tests
        run: npm test -- --ci
        working-directory: ./Frontend
